workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - google-services
    scripts:
      - name: Decode google-services.json
        script: echo $GSERVICES_JSON_B64 | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
      - name: Change package name
        script: sed -i.bak 's/com.livehelperchat.mobile/com.dev_shadin.livechat/g' $CM_BUILD_DIR/android/app/build.gradle
      - name: Fix Gradle settings # <--- নতুন লাইন
        script: sed -i.bak 's/include ":app"/include ":app"\napply from: "..\/node_modules\/@react-native-community\/cli-platform-android\/native_modules.gradle"; applyNativeModulesSettingsGradle(settings)/g' $CM_BUILD_DIR/android/settings.gradle
      - name: Fix app_plugin_loader # <--- নতুন লাইন
        script: sed -i.bak "s/apply from: \"..\/..\/..\/..\/..\/..\/programs\/flutter\/packages\/flutter_tools\/gradle\/app_plugin_loader.gradle\"//g" $CM_BUILD_DIR/android/app/build.gradle
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
