name: livehelp
description: A messenger for Live Helper Chat
version: 1.0.25+43
publish_to: 'none' # Prevent accidental publishing

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  after_layout: ^1.2.0
  http: ^1.1.0
  flutter_speed_dial: ^7.0.0
  flutter_html: 3.0.0-beta.2
  url_launcher: ^6.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_linkify: ^5.0.2
  cupertino_icons: ^1.0.6
  record: ^5.0.4
  toastification: ^1.2.0
  http_parser: ^4.0.2
  file_picker: ^6.1.1
  mime: ^1.0.4
  photo_view: ^0.14.0
  voice_message_package: ^2.2.1
  just_audio: ^0.9.36
  flutter_downloader: ^1.11.0
  cached_network_image: ^3.3.0
  flutter_file_downloader: ^1.2.1
  open_file: ^3.3.2
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "graphics/icon.png"
  android: true
  ios: false
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - graphics/header.jpg
    - assets/audio/sample.mp3
    - assets/images/
